# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamilunicode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TamilUncode',
            new_name='TamilUnicode',
        ),
    ]
